version: '3.8'
services:
  app:
    container_name: gemini-account-measure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=gemini-account-measure-database
  mysql:
      container_name: gemini-account-measure-database
      image: mysql:8.0
      ports:
        - "3306:3306" 
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data: